# -*- coding: utf-8 -*-
"""newsapi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QeI-XM0kfURmg6SwIItSoQ8uqA7zXsD
"""

pip install newsapi-python

with open('/content/api.txt') as f:
    lines = f.readlines()

lines[0]

from newsapi import NewsApiClient

# Init
newsapi = NewsApiClient(api_key=lines[0])

# /v2/top-headlines
# top_headlines = newsapi.get_top_headlines(q='bitcoin', language='en')
top_headlines = newsapi.get_top_headlines(sources='bbc-news')

# /v2/everything
# all_articles = newsapi.get_everything(q='bitcoin', sources='bbc-news,the-verge', domains='bbc.co.uk,techcrunch.com', from_param='2017-12-01', to='2017-12-12', language='en', sort_by='relevancy', page=2)

# /v2/top-headlines/sources
sources = newsapi.get_sources()

top_headlines

top_headlines['articles'][0]

import pandas as pd

df = pd.DataFrame (top_headlines['articles'][0], columns = ['source', 'author','title','description','url','urlToImage','publishedAt','content'])
print (df)

df1 = pd.DataFrame (top_headlines['articles'][0])
print (df1)

df1

df4 = pd.DataFrame (top_headlines['articles'])
print (df4)

df4

df4.to_csv('Newsapi_output.csv')