# -*- coding: utf-8 -*-
"""Copy of newsapi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V4moMAa0VDylfofK8rVzrOB1NpaztS_9
"""

pip install newsapi-python

with open('/content/api.txt') as f:
    lines = f.readlines()

lines[0]

from newsapi import NewsApiClient

# initialize the api client
newsapi = NewsApiClient(api_key=lines[0])

# get the top headlines from bbc news
top_headlines = newsapi.get_top_headlines(sources='bbc-news')

top_headlines

top_headlines['articles'][0]

import pandas as pd

df4 = pd.DataFrame (top_headlines['articles'])
print (df4)

df4

df4.to_csv('Newsapi_output.csv',sep = ',', encoding = 'utf-8',index = False,quotechar = '"')

